
name: Publish Gem

on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Git identity
        run: |
          git config --global user.email "thesamuelralak@gmail.com"
          git config --global user.name "Samuel Ralak"

      - name: Release Gem
        uses: cadwallion/publish-rubygems-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GPR_AUTH_TOKEN}}
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
          RELEASE_COMMAND: rake release